// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDc893W3FfFDPKmZIIt_ouXP4FemGurQ_E',
    appId: '1:350998465544:web:9b79d020094472769c55bd',
    messagingSenderId: '350998465544',
    projectId: 'telecomsupporttask',
    authDomain: 'telecomsupporttask.firebaseapp.com',
    storageBucket: 'telecomsupporttask.firebasestorage.app',
    measurementId: 'G-JVLG3NE8KZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMEzMizCyz4HK6M8rbJw3Mb7MOSvXab6I',
    appId: '1:350998465544:android:744888c520dcb60c9c55bd',
    messagingSenderId: '350998465544',
    projectId: 'telecomsupporttask',
    storageBucket: 'telecomsupporttask.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5NBVDGYBBHOi0DMDTZir3Aki7lzSgKOY',
    appId: '1:350998465544:ios:4e1ac157293d237e9c55bd',
    messagingSenderId: '350998465544',
    projectId: 'telecomsupporttask',
    storageBucket: 'telecomsupporttask.firebasestorage.app',
    iosBundleId: 'com.example.telecomSupportApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5NBVDGYBBHOi0DMDTZir3Aki7lzSgKOY',
    appId: '1:350998465544:ios:4e1ac157293d237e9c55bd',
    messagingSenderId: '350998465544',
    projectId: 'telecomsupporttask',
    storageBucket: 'telecomsupporttask.firebasestorage.app',
    iosBundleId: 'com.example.telecomSupportApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDc893W3FfFDPKmZIIt_ouXP4FemGurQ_E',
    appId: '1:350998465544:web:82728c579219311e9c55bd',
    messagingSenderId: '350998465544',
    projectId: 'telecomsupporttask',
    authDomain: 'telecomsupporttask.firebaseapp.com',
    storageBucket: 'telecomsupporttask.firebasestorage.app',
    measurementId: 'G-SPPZ2YC2ZW',
  );
}
